### ISSUE TITLE
audacious throws undefined symbol: init_vgmstream_bfwav

### ISSUE THREAD

**Issue by eppixx** [eppixx/audacious-vgmstream#2]
the version bump caused throwing an error when loading vgmstream in audacious

**Comment by TricksterGuy** [comment]
Hey eppixx, I just happened upon this issue (and the pull request a few days ago)

I have already updated this to 3.5.1 and its in a pull request in the main vgmstream repo (I don't believe its merged into the main one yet though), I did base it off your code and I have also given you credit, but I had came across the same issue while I was updating it and had already fixed it.

**Comment by eppixx** [comment]
Hi TricksterGuy,
that is nice to hear.
Is there a way to relate my repo to yours, or do I need to fork yours.
I'm pretty new to developing in the public :D

**Comment by TricksterGuy** [comment]
Yeah my repo was a fork of vgmstream if the pull request over there gets accepted then its just a matter of you pulling from vgmstream (I believe)

also kinda new to developing with other here when multiple forks are involved.

**Comment by TricksterGuy** [comment]
Also here is the pull request 

https://github.com/kode54/vgmstream/pull/6

**Comment by hoodlum47** [comment]
Any news on this?

**Comment by TricksterGuy** [comment]
the pull request I mentioned in my last post was accepted on September 14th, this has been fixed for awhile now.

I believe its best if we just fork kode54/vgmstream and just submit pull requests if anything changes on the audacious side.

**Comment by eppixx** [comment]
Here is the full URL to the official repo:
https://github.com/kode54/vgmstream
